clash/src/main.rs, clash_lib/src/app/dispatcher/mod.rs, clash_lib/src/app/dispatcher/tracked.rs, clash_lib/src/proxy/direct/mod.rs, clash_lib/src/proxy/fallback/mod.rs, clash_lib/src/proxy/loadbalance/mod.rs, clash_lib/src/proxy/mocks.rs, clash_lib/src/proxy/mod.rs, clash_lib/src/proxy/reject/mod.rs, clash_lib/src/proxy/relay/mod.rs, clash_lib/src/proxy/selector/mod.rs, clash_lib/src/proxy/shadowsocks/mod.rs, clash_lib/src/proxy/trojan/mod.rs, clash_lib/src/proxy/urltest/mod.rs, clash_lib/src/proxy/vmess/mod.rs, scripts/check_socks5.py
=> display udp proxy chain names

.github/workflows/ci.yml, clash_lib/src/app/api/handlers/config.rs, clash_lib/src/config/def.rs, clash_lib/src/proxy/converters/trojan.rs, clash_lib/src/proxy/converters/vmess.rs, clash_lib/src/proxy/selector/mod.rs, clash_lib/src/proxy/utils/provider_helper.rs, clash_lib/src/session.rs
=> update ci toolchain setup

clash/tests/data/config/wg.yaml, clash_lib/src/proxy/converters/wireguard.rs, clash_lib/src/proxy/wg/device.rs, clash_lib/src/proxy/wg/mod.rs, clash_lib/src/proxy/wg/wireguard.rs
=> enable ipv6 on wireguard

clash_lib/src/proxy/transport/grpc.rs, clash_lib/src/proxy/vmess/vmess_impl/stream.rs
=> cleanup some useless prints

clash_lib/src/app/remote_content_manager/mod.rs, clash_lib/src/proxy/converters/trojan.rs, clash_lib/src/proxy/converters/vmess.rs, clash_lib/src/proxy/fallback/mod.rs, clash_lib/src/proxy/options.rs, clash_lib/src/proxy/selector/mod.rs, clash_lib/src/proxy/trojan/mod.rs, clash_lib/src/proxy/vmess/mod.rs
=> Fix grpc failure to connect to some servers

Cargo.lock, Cargo.toml
=> bump v0.1.13

clash_lib/src/proxy/tun/inbound.rs
=> fix tun exit unexpectedly

.github/workflows/ci.yml
=> fix ci toolchain

clash_lib/src/app/dns/server/mod.rs
=> bring back tun fake ip

.github/workflows/ci.yml
=> stash artifacts for branches

clash_lib/src/app/dns/dns_client.rs, clash_lib/src/proxy/utils/mod.rs
=> lazy initialize DNS clients

Cargo.lock, README.md, clash/tests/data/config/tor.yaml, clash_lib/Cargo.toml, clash_lib/src/app/dispatcher/tracked.rs, clash_lib/src/app/outbound/manager.rs, clash_lib/src/app/remote_content_manager/mod.rs, clash_lib/src/app/remote_content_manager/providers/proxy_provider/proxy_set_provider.rs, clash_lib/src/common/http.rs, clash_lib/src/config/internal/config.rs, clash_lib/src/config/internal/proxy.rs, clash_lib/src/proxy/converters/mod.rs, clash_lib/src/proxy/converters/tor.rs, clash_lib/src/proxy/mod.rs, clash_lib/src/proxy/shadowsocks/simple_obfs/http.rs, clash_lib/src/proxy/tor/mod.rs, clash_lib/src/proxy/tor/stream.rs, clash_lib/src/proxy/transport/tls.rs, clash_lib/src/proxy/transport/ws/mod.rs, clash_lib/src/proxy/urltest/mod.rs, clash_lib/src/proxy/vmess/vmess_impl/stream.rs, clash_lib/src/proxy/wg/wireguard.rs
tor outboud support
```
proxies:
- name: "tor"
type: tor
```
=> tor outboud support

.github/workflows/ci.yml
=> pin ci rustc version

clash/tests/data/config/simple.yaml, clash_lib/src/proxy/selector/mod.rs
=> fix selector cache not found after swithing profile(stale cache)

.github/workflows/ci.yml
=> disable ci rust cache

clash_lib/src/config/internal/proxy.rs, clash_lib/src/proxy/converters/wireguard.rs, clash_lib/src/proxy/wg/mod.rs, clash_lib/src/proxy/wg/wireguard.rs
=> support wg reserved bits

clash_lib/src/proxy/vmess/mod.rs
https://github.com/Watfaq/clash-rs/issues/322
see the discussion in the issue instead
=> fix opt.host in http2 config

Cargo.lock, clash_lib/Cargo.toml, clash_lib/build.rs, clash_lib/src/common/crypto.rs, clash_lib/src/proxy/vmess/vmess_impl/header.rs, clash_lib/src/proxy/vmess/vmess_impl/stream.rs, clash_lib/src/proxy/vmess/vmess_impl/user.rs
remove boringssl
https://github.com/Watfaq/clash-rs/issues/205
=> remove boringssl

clash_lib/src/proxy/shadowsocks/simple_obfs/http.rs
https://github.com/Watfaq/clash-rs/issues/426
BG: the issue has been fixed once, after that, i did do some in-the-real-world tests, but some situation is not triggered/covered. and it seems that the bugfix has some problems: 
1. clone_from_slice is misused, and will cause panic.
2. the buffered fist response shall be checked at the beginning of poll_read
so i mainly refered to [clash.meta's impl](https://github.com/MetaCubeX/mihomo/blob/48e481d0a22302c215878bd53e0b81547f4f45de/transport/simple-obfs/http.go#L28) this time. 
I still couldn't trigger the modified code in my computer, but the code should be alright this time. 
But i got to think, in each protocol's impl, there may exists some situations that is not covered by our docker test. Shall we figure out some approach to verify each …
=> fix: use put_slice instead of clone_from_slice in httpobfs

clash/tests/data/config/rules.yaml, clash_lib/src/app/api/mod.rs
=> fix: support non stardard API listen addr

clash_lib/src/proxy/shadowsocks/mod.rs, clash_lib/src/proxy/shadowsocks/simple_obfs/tls.rs, clash_lib/src/proxy/utils/test_utils/consts.rs
https://github.com/Watfaq/clash-rs/issues/426
add docker test support for obfs(only on amd64), and found the bug in obfs's tls impl, and have it fixed
fix: fix bug in shadowsocks obfs's tls mode
=> fix: fix state machine logic error in obfs's tls impl; add docker tests for obfs

Cargo.lock, clash_lib/Cargo.toml, clash_lib/src/app/logging.rs, docker/docker-compose.yml
read OTLP env vars from https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/
=> feat: honor OTLP env vars

clash_lib/src/app/api/mod.rs
```
$env:RUST_LOG="tower_http=trace"
```
to enable HTTP logging
=> fix: fixed broken ws api

clash_lib/src/proxy/converters/tuic.rs, clash_lib/src/proxy/tuic/handle_task.rs, clash_lib/src/proxy/tuic/mod.rs, clash_lib/src/proxy/tuic/types.rs
=> refactor: tuic

.github/workflows/ci.yml, Cargo.lock, clash_lib/Cargo.toml, clash_lib/build.rs, clash_lib/src/app/dispatcher/dispatcher_impl.rs, clash_lib/src/app/dns/system.rs, clash_lib/src/app/logging.rs, clash_lib/src/lib.rs, clash_lib/src/proxy/shadowsocks/mod.rs, clash_lib/src/proxy/tuic/mod.rs, clash_lib/src/proxy/tuic/types.rs, clash_lib/src/proxy/tun/inbound.rs, clash_lib/src/proxy/utils/mod.rs, clash_lib/src/proxy/utils/socket_helpers.rs, rust-toolchain.toml
=> fix: some fixes

Cargo.lock, clash_lib/Cargo.toml, clash_lib/src/lib.rs
remove the useless `setup_tests` to fix windows link error 1120 of `ctor::ctor` functions
=> fix: remove setup_tests, try to fix CI error on windows

clash_lib/src/app/dns/system.rs, clash_lib/src/proxy/tun/inbound.rs, clash_lib/src/proxy/utils/socket_helpers.rs
=> fix: deal with ipv6 dns

clash_lib/src/app/inbound/network_listener.rs
=> fix: new iface API?

clash_lib/Cargo.toml, clash_lib/src/app/outbound/manager.rs, clash_lib/src/app/remote_content_manager/providers/proxy_provider/proxy_set_provider.rs, clash_lib/src/config/internal/proxy.rs, clash_lib/src/proxy/converters/mod.rs, clash_lib/src/proxy/mod.rs, clash_lib/src/proxy/relay/mod.rs, clash_lib/src/proxy/utils/test_utils/consts.rs
=> build: enable feature flags for outbounds

.github/workflows/ci.yml
=> build: fix github actions rate limit

clash_lib/src/app/dns/dhcp.rs, clash_lib/src/app/dns/helper.rs, clash_lib/src/app/dns/mod.rs, clash_lib/src/app/dns/resolver/enhanced.rs, clash_lib/src/app/dns/resolver/mod.rs, clash_lib/src/app/dns/resolver/system_linux.rs, clash_lib/src/app/dns/resolver/system_non_linux.rs
bring back system dns on non linux, cause trouble on iOS not being able to read /etc/resolve.conf
=> refactor(dns): use system dns on non linux

Cargo.lock, clash/tests/data/config/rules.yaml, clash_lib/Cargo.toml, clash_lib/src/app/api/handlers/dns.rs, clash_lib/src/app/api/handlers/memory.rs, clash_lib/src/app/api/handlers/mod.rs, clash_lib/src/app/api/handlers/restart.rs, clash_lib/src/app/api/mod.rs, clash_lib/src/app/dispatcher/statistics_manager.rs
=> feat(api): implement some control APIs

Cargo.lock, clash/tests/data/config/config.test.yaml, clash/tests/data/config/rules.yaml, clash_lib/Cargo.toml, clash_lib/src/proxy/tun/inbound.rs, clash_lib/src/proxy/utils/mod.rs, clash_lib/src/proxy/utils/platform/apple.rs, clash_lib/src/proxy/utils/platform/mod.rs, clash_lib/src/proxy/utils/platform/unix.rs, clash_lib/src/proxy/utils/platform/win.rs, clash_lib/src/proxy/utils/socket_helpers.rs
=> feat(tun): fix tun mode on Windows

.cargo/config.toml, clash/tests/data/config/rules.yaml, clash_lib/src/app/dns/config.rs, clash_lib/src/app/dns/dhcp.rs, clash_lib/src/app/dns/dns_client.rs, clash_lib/src/app/dns/helper.rs, clash_lib/src/app/dns/resolver/enhanced.rs, clash_lib/src/app/logging.rs, clash_lib/src/common/errors.rs, clash_lib/src/common/http.rs, clash_lib/src/lib.rs, clash_lib/src/proxy/direct/mod.rs, clash_lib/src/proxy/shadowsocks/mod.rs, clash_lib/src/proxy/socks/inbound/stream.rs, clash_lib/src/proxy/socks/outbound/mod.rs, clash_lib/src/proxy/tor/mod.rs, clash_lib/src/proxy/tuic/compat.rs, clash_lib/src/proxy/tuic/mod.rs, clash_lib/src/proxy/tuic/types.rs, clash_lib/src/proxy/tun/inbound.rs, clash_lib/src/proxy/utils/platform/apple.rs, clash_lib/src/proxy/utils/platform/win.rs, clash_lib/src/proxy/utils/proxy_connector.rs, clash_lib/src/proxy/utils/socket_helpers.rs, clash_lib/src/proxy/wg/wireguard.rs
=> feat(dns): bind interface on dns connections

clash/tests/data/config/rules.yaml, clash_lib/src/config/def.rs, clash_lib/src/config/internal/config.rs, clash_lib/src/proxy/tun/inbound.rs
try to fix "failed to write whole buffer"
=> fix(tun): larger mtu on win

Cargo.lock, clash_lib/Cargo.toml
=> fix: disable tor compresson and get rid of lzma runtime dep

.github/dependabot.yaml
=> ci: add dependencies group update

.github/cliff.toml, .github/workflows/ci.yml
=> ci: change cliff config

Cargo.lock, clash_lib/src/proxy/converters/shadowsocks.rs, clash_lib/src/proxy/shadowsocks/mod.rs
=> style(logging): suppress dep plugin warning

clash/build.rs
=> fix: broken ci version

.github/cliff.toml
=> fix(git-cliff): update config for adding contributors to changelog

clash_lib/src/proxy/tun/routes/mod.rs, clash_lib/src/proxy/tun/routes/other.rs
=> fix: build on other plats

clash_lib/src/config/def.rs
=> feat(config): apply yaml anchors and refs

.github/workflows/ci.yml
=> build(ci): Update ci.yml

clash/tests/data/config/rules.yaml, clash_lib/src/config/def.rs, clash_lib/src/config/internal/config.rs
=> feat(tun): dns hijack config compatible

clash_lib/src/proxy/shadowsocks/mod.rs
=> feat(proxy): support shadowsocks 2022

clash_lib/src/app/api/handlers/connection.rs, clash_lib/src/app/api/handlers/provider.rs, clash_lib/src/app/api/handlers/proxy.rs
=> fix(api): axum new uri format

clash_lib/src/app/dns/filters.rs, clash_lib/src/app/logging.rs, clash_lib/src/app/profile/mod.rs, clash_lib/src/app/router/mod.rs, clash_lib/src/app/router/rules/geoip.rs, clash_lib/src/common/io.rs, clash_lib/src/common/mmdb.rs, clash_lib/src/config/def.rs, clash_lib/src/lib.rs, clash_lib/src/proxy/group/selector/mod.rs, clash_lib/src/proxy/hysteria2/congestion.rs, clash_lib/src/proxy/hysteria2/salamander.rs, clash_lib/src/proxy/hysteria2/udp_hop.rs, clash_lib/src/proxy/shadowsocks/datagram.rs, clash_lib/src/proxy/shadowsocks/shadow_tls/stream.rs, clash_lib/src/proxy/tuic/types.rs, clash_lib/src/proxy/wg/wireguard.rs
check and fix typos (basically all of them) with https://github.com/crate-ci/typos
- install `cargo install typos-cli`
- run `typos -w clash_lib` (fix mode)
=> fix: fix typos with typos-cli

Cargo.lock, Cross.toml, clash_lib/Cargo.toml, clash_lib/src/proxy/ssh/auth.rs, clash_lib/src/proxy/ssh/mod.rs, clash_lib/src/proxy/utils/test_utils/docker_utils/docker_runner.rs
1. optimize: simplify `Auth::auth` signature, only try the auth method when specific arguments(password, private key, totp) is specified, without throwing and catching error in `Auth::auth`
2. test case: since ssh docker test is not added to ci, the action didn't cover ssh protocol, so the version of `rand_core` brought about some troubles after the version bump. it can be solved by specific `rand_chacha` version in dev-dependencies
3. `ci.yaml` for ssh docker test will be fixed in another PR
since ssh docker test is not added to CI, the test is ran **LOCALLY** on my desktop and VPS, and they still passed
=> ssh: fix ssh test case & optimize ssh auth code style

clash/tests/data/config/empty.yaml, clash/tests/data/config/hysteria.json, clash_lib/src/proxy/converters/hysteria2.rs, clash_lib/src/proxy/hysteria2/mod.rs, clash_lib/src/proxy/hysteria2/udp_hop.rs, clash_lib/src/proxy/utils/test_utils/docker_utils/config_helper.rs, clash_lib/src/proxy/utils/test_utils/docker_utils/consts.rs
1. use config without outbound handler in docker test, or it will rely on feature flags like "shadowsocks"
2. add hysteria2 tcp test
=> test: hysteria2 test(tcp only)

clash_lib/src/proxy/converters/shadowsocks.rs, clash_lib/src/proxy/shadowsocks/mod.rs, clash_lib/src/proxy/shadowsocks/v2ray/mod.rs
support shadowsocks v2ray plugin(mux is not done yet)
- support shadowsocks v2ray plugin(mux is not done yet)
=> feat(proxy): support ss v2ray plugin

clash_lib/src/common/tls.rs, clash_lib/src/proxy/hysteria2/mod.rs, clash_lib/src/proxy/transport/tls.rs, clash_lib/src/proxy/tuic/mod.rs
merge tls verifiers into one type, cleanup some redundant code
=> clean up useless code

clash_lib/src/config/internal/proxy.rs, clash_lib/src/lib.rs, clash_lib/src/proxy/converters/hysteria2.rs, clash_lib/src/proxy/hysteria2/codec.rs, clash_lib/src/proxy/hysteria2/datagram.rs, clash_lib/src/proxy/hysteria2/mod.rs
support hysteria2 udp
- support hysteria2 udp
=> feat: support hysteria2 udp

.github/workflows/ci.yml, Cross.toml, clash_lib/src/lib.rs, rust-toolchain.toml
=> build: fix older nightly toolchain

clash/tests/data/config/rules.yaml, clash_lib/src/app/api/middlewares/auth.rs, clash_lib/src/app/api/mod.rs, scripts/logs.py
=> feat(api): support ws auth header

.cargo/config.toml, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, Cross.toml, README.md, clash/Cargo.toml, clash/src/main.rs, clash_lib/src/app/dns/helper.rs, clash_lib/src/app/dns/resolver/mod.rs, clash_lib/src/app/outbound/manager.rs, clash_lib/src/app/remote_content_manager/http_client.rs, clash_lib/src/app/router/mod.rs, clash_lib/src/common/errors.rs, clash_lib/src/common/http/client.rs, clash_lib/src/config/internal/rule.rs, clash_lib/src/lib.rs, clash_lib/src/proxy/transport/shadow_tls/mod.rs, clash_lib/src/proxy/transport/tls.rs, clash_lib/src/session.rs
=> feat: add sentry and panic report

Cargo.toml
=> build(size): fix app size

clash_lib/src/proxy/tun/inbound.rs
https://github.com/xjasonlyu/tun2socks/issues/300
=> feat(tun): support wintun guid

clash_lib/src/app/router/mod.rs, clash_lib/src/app/router/rules/geoip.rs, clash_lib/src/app/router/rules/ipcidr.rs, clash_lib/src/session.rs
=> fix(router): match ipcidr if request host is ip

Cargo.lock, clash_lib/Cargo.toml, clash_lib/src/proxy/shadowquic/mod.rs
This fixes issue #790 which is caused by upstream improper use of Notify
- #790
- https://github.com/spongebob888/shadowquic/issues/16
=> Fix shadowquic udp over datagram ci failed #790

Cargo.lock, clash_lib/Cargo.toml
=> fix: bump version to fix shadowquic udp ci failed

clash_lib/src/app/api/mod.rs, clash_lib/src/config/def.rs, clash_lib/src/config/internal/config.rs, clash_lib/src/config/internal/convert/general.rs
api security: no longer allow external-controller running on non-local address without proper auth secret and CORS original setup
=> feat(api)!: secure external controller when not listening on lan

clash_lib/Cargo.toml, clash_lib/src/app/net/mod.rs, clash_lib/src/proxy/tun/routes/mod.rs, clash_lib/src/proxy/tun/routes/windows.rs
This PR replaces cmd style auto route to windows api
This is done by reimplementing `add_route`
Besides this, it's also found dns hijacking is never working on windows.  This is because tun dns server is not set and
windows won't query dns through tun in such case. To solve this `set_dns_v4/set_dns_v6` is provided to add dns servers.
The default dns server is hard coded to be `1.1.1.1`. This is not a good idea. But we can't set dns server to clash itself  because windows only support dns server on port 53.
If you have better ideas, I'm glad to fix this.
Also, `add_address` api is implemented to provide ipv6 support in the future.
This is experimental and may need more test.
=> refactor(tun): replace cmd style auto route with api on windows

.github/workflows/spell-check.yml, README.md, _typos.toml, clash/build.rs, clash/src/main.rs, clash_lib/src/app/net/mod.rs, clash_lib/src/app/remote_content_manager/providers/rule_provider/provider.rs, clash_lib/src/config/def.rs, clash_lib/src/config/internal/convert/listener.rs, clash_lib/src/proxy/shadowquic/compat.rs, clash_lib/src/proxy/shadowquic/mod.rs, clash_lib/src/proxy/tproxy/mod.rs, clash_lib/src/proxy/tun/inbound.rs, clash_lib/src/proxy/vmess/mod.rs
=> style(spelling): add spell check actions

.github/workflows/ci.yml, clash_lib/src/app/api/mod.rs, clash_lib/src/app/inbound/network_listener.rs, clash_lib/src/app/net/mod.rs, clash_lib/src/config/internal/listener.rs, clash_lib/tests/api_tests.rs, clash_lib/tests/common/mod.rs
=> fix(test): fixed api test failure on windows

clash_lib/src/app/outbound/manager.rs, clash_lib/src/app/remote_content_manager/providers/proxy_provider/plain_provider.rs, clash_lib/src/proxy/utils/provider_helper.rs
=> fix(api): global proxy names duplicates

clash_lib/src/app/api/handlers/provider.rs, clash_lib/src/app/outbound/manager.rs
=> fix(api): fix provider proxy endpoint and proxies endpoint returning provider proxies

Cargo.lock, _typos.toml, clash-lib/Cargo.toml, clash-lib/src/app/dispatcher/tracked.rs, clash-lib/src/proxy/mod.rs, clash-lib/src/proxy/tproxy/mod.rs, clash-lib/src/proxy/transport/simple_obfs/http.rs, clash-lib/src/proxy/transport/simple_obfs/tls.rs, clash-lib/src/proxy/transport/ws/websocket.rs, clash-lib/src/proxy/transport/ws/websocket_early_data.rs, clash-lib/src/proxy/utils/socket_helpers.rs
=> build(deps): upgrade a few deps

clash-lib/src/proxy/tunnel/mod.rs
=> adding dual stack for tunnel

clash-bin/Cargo.toml, clash-lib/Cargo.toml, clash-lib/src/app/inbound/manager.rs, clash-lib/src/app/inbound/network_listener.rs, clash-lib/src/config/internal/convert/listener.rs, clash-lib/src/config/internal/listener.rs, clash-lib/src/proxy/mod.rs, clash-lib/src/proxy/redir/mod.rs, clash-lib/src/proxy/redir/redir.sh, clash-lib/src/session.rs
Many plugins on openwrt using redirect to proxy tcp traffic. Adding this kind of inbound may be helpful
=> feat(redir): redir proxy implementation

Cargo.lock, Cargo.toml
=> build(deps): bump async-process to 2.4.0

clash-lib/src/app/dns/config.rs
=> fix(fallback-filter): geoip-code failed to match

Cargo.lock, clash-netstack/Cargo.toml, clash-netstack/examples/README.md, clash-netstack/examples/netstack_smoltcp.rs, clash-netstack/src/tcp_listener.rs
=> perf(tun): align with other impls

.github/workflows/ci.yml, Cargo.lock, clash-dns/Cargo.toml, clash-dns/src/handler.rs, clash-lib/Cargo.toml, clash-lib/src/app/dispatcher/statistics_manager.rs, clash-lib/src/app/remote_content_manager/mod.rs, clash-lib/src/app/remote_content_manager/providers/http_vehicle.rs, clash-lib/src/common/errors.rs, clash-lib/src/proxy/utils/test_utils/docker_utils/mod.rs
=> ci: mips build jobs
