- clash_lib/src/proxy/vmess/mod.rs
* grpc with **h2c**: test ok as expect
* h2 with **h2c**: small page can read as expect
* huge page, like: `https://www.aliyun.com` or `https://cloud.tencent.com` could read really small - seems can't finish in a minute.
* I haven't tested it in h2 with tls
It seems buffer is really small?
> fix(vmess): add h2c support for h2 and grpc transport

- Cargo.lock
- clash_lib/Cargo.toml
- clash_lib/src/app/api/handlers/config.rs
- clash_lib/src/common/mmdb.rs
- clash_lib/src/lib.rs
> add config reload api

- clash_lib/src/common/tls.rs
> allow self signed v1 ssl cert

- .cargo/config
- .gitmodules
- Cargo.lock
- clash_lib/Cargo.toml
- clash_lib/src/common/crypto.rs
- clash_lib/src/lib.rs
- clash_lib/src/proxy/transport/tls.rs
> use aes crate and get rid of boring fork

- .gitignore
- Cargo.lock
- clash_lib/Cargo.toml
- clash_lib/src/app/outbound/manager.rs
- clash_lib/src/app/remote_content_manager/providers/proxy_provider/proxy_set_provider.rs
- clash_lib/src/config/internal/proxy.rs
- clash_lib/src/lib.rs
- clash_lib/src/proxy/converters/mod.rs
- clash_lib/src/proxy/converters/tuic.rs
- clash_lib/src/proxy/mod.rs
- clash_lib/src/proxy/tuic/compat.rs
- clash_lib/src/proxy/tuic/handle_stream.rs
- clash_lib/src/proxy/tuic/handle_task.rs
- clash_lib/src/proxy/tuic/mod.rs
- clash_lib/src/proxy/tuic/types.rs
Impl https://github.com/Watfaq/clash-rs/issues/190
Work in progress
> Support TUIC

- .github/workflows/ci.yml
- clash_lib/build.rs
- clash_lib/src/lib.rs
> fix docker tests trigger on CI

- Cargo.lock
- Cargo.toml
- clash_lib/Cargo.toml
- clash_lib/src/app/inbound/network_listener.rs
- clash_lib/src/proxy/converters/shadowsocks.rs
- clash_lib/src/proxy/shadowsocks/mod.rs
- clash_lib/src/proxy/shadowsocks/shadow_tls/connector.rs
- clash_lib/src/proxy/shadowsocks/shadow_tls/mod.rs
- clash_lib/src/proxy/shadowsocks/shadow_tls/stream.rs
- clash_lib/src/proxy/shadowsocks/shadow_tls/utils.rs
- clash_lib/src/proxy/trojan/mod.rs
- clash_lib/src/proxy/utils/socket_helpers.rs
- clash_lib/src/proxy/utils/test_utils/config_helper.rs
- clash_lib/src/proxy/utils/test_utils/consts.rs
- clash_lib/src/proxy/utils/test_utils/docker_runner.rs
- clash_lib/src/proxy/utils/test_utils/mod.rs
- clash_lib/src/proxy/vmess/mod.rs
implement shadow-tls protocol's client(v3)
https://github.com/Watfaq/clash-rs/issues/321
see the background mentioned in the issue. 
solution:
1. patch the rustls & tokio-rusls crates, support customed client id in the client hello
2. implement shadow-tls's client v3
3. add shadow-tls option in shadowsocks's plugins
Tests has been done in my ubuntu 22.04.
Support shadow-tls(v3 only)
> feat: support shadow-tls(v3 only)

- clash_lib/src/proxy/shadowsocks/simple_obfs/http.rs
https://github.com/Watfaq/clash-rs/issues/426
maintain a BytesMut in the stream to buffer the data that has already been read but cannot be passed to poll_read's buf, similar to other impls of `AsyncRead` in outbound handlers.
fix: fix buf out of len issue in shadowsocks's simple_obfs's http implementation
> fix: check read_buf's remaining before put_slice in obfs's http impl

- .github/Dockerfile
- .github/workflows/ci.yml
- Cargo.lock
- Dockerfile
- clash_lib/Cargo.toml
- clash_lib/src/proxy/shadowsocks/mod.rs
None
1. I need to deploy the clash proxy in a containerized environment.
2. Some proxy service providers only support rc4-md5 cipher.
Tweaked CI build to add x86_64-unknown-linux-musl target
Added docker image based on x86_64-unknown-linux-musl package.
Added rc4-md5 cipher parsing.
**You need to add two action secrets: DOCKER_USERNAME and DOCKER_PASSWORD.**
> feate: linux-musl target,docker image,add rc4-md5 cipher

- Makefile
- clash/tests/data/config/rules.yaml
- clash_lib/Cargo.toml
- clash_lib/src/app/logging.rs
- clash_lib/src/common/defer.rs
- clash_lib/src/common/mod.rs
- clash_lib/src/config/def.rs
- clash_lib/src/config/internal/config.rs
- clash_lib/src/proxy/tun/inbound.rs
- clash_lib/src/proxy/tun/mod.rs
- clash_lib/src/proxy/tun/routes/linux.rs
- clash_lib/src/proxy/tun/routes/macos.rs
- clash_lib/src/proxy/tun/routes/mod.rs
- clash_lib/src/proxy/tun/routes/other.rs
- clash_lib/src/proxy/tun/routes/windows.rs
- clash_lib/src/proxy/utils/platform/win.rs
#559 
https://learn.microsoft.com/en-us/windows/win32/rras/add-and-update-routes-using-rtmaddroutetodest
```
tun:
enable: true
device-id: "dev://utun1989"
route-all: false
routes:
- 0.0.0.0/1
- 128.0.0.0/1
```
> feat(tun): windows auto-route

- clash_lib/src/app/outbound/manager.rs
- clash_lib/src/config/internal/proxy.rs
- clash_lib/src/proxy/fallback/mod.rs
- clash_lib/src/proxy/loadbalance/mod.rs
- clash_lib/src/proxy/mod.rs
- clash_lib/src/proxy/options.rs
- clash_lib/src/proxy/relay/mod.rs
- clash_lib/src/proxy/selector/mod.rs
- clash_lib/src/proxy/urltest/mod.rs
Nope
Mihomo introduce the `icon` field for showing a custom icon processed by GUI.
Doc link: <https://wiki.metacubex.one/config/proxy-groups/?h=icon#icon>
What's more, it seems that:
* we could introduce the [enumflags2](https://crates.io/crates/enumflags2) for better group match(reducing duplicate code).
* we could shared the opts and serialize via `serde(flatten)`. The behavior should be similar to the anonymous field of golang. Doc ref: <https://serde.rs/attr-flatten.html>
> feat: compatiable with mihomo `icon` field

- .github/Dockerfile
After testing and using the containerized environment, I found that I forgot to give executable permissions to the clash binary file inside the container, so I'll adjust it.
Fixing `/usr/bin/clash` not having executable permissions in the image
> fix: executable privilege

- clash/tests/data/config/rules.yaml
- clash_lib/src/proxy/tun/inbound.rs
- clash_lib/src/proxy/tun/routes/macos.rs
- clash_lib/src/proxy/tun/routes/mod.rs
#559 
need to add an extra scoped default route on macos for higher priority
> feat(tun): auto route on macos

- clash_lib/src/app/router/mod.rs
- clash_lib/src/app/router/rules/geoip.rs
- clash_lib/src/app/router/rules/ipcidr.rs
- clash_lib/src/proxy/tun/inbound.rs
- clash_lib/src/session.rs
> fix(rule): rule match order with ip resolve

- clash_lib/src/proxy/tuic/mod.rs
- clash_lib/src/proxy/utils/platform/win.rs
> fix(tuic): not connecting on windows

- Cargo.lock
- clash/tests/data/config/rules.yaml
- clash/tests/data/config/tproxy.yaml
- clash_lib/Cargo.toml
- clash_lib/src/app/inbound/manager.rs
- clash_lib/src/app/inbound/network_listener.rs
- clash_lib/src/proxy/datagram.rs
- clash_lib/src/proxy/mod.rs
- clash_lib/src/proxy/socks/inbound/datagram.rs
- clash_lib/src/proxy/socks/inbound/stream.rs
- clash_lib/src/proxy/tproxy/iptables.sh
- clash_lib/src/proxy/tproxy/mod.rs
- clash_lib/src/proxy/tun/datagram.rs
- clash_lib/src/proxy/tun/inbound.rs
- clash_lib/src/proxy/tun/mod.rs
- clash_lib/src/session.rs
#73 
largely based on and supercedes #343 
without iptables integration
https://github.com/kristrev/tproxy-example/blob/master/README.md
https://powerdns.org/tproxydoc/tproxy.md.html
> feat(tproxy): support tproxy on Linux

- Cargo.lock
- clash_lib/src/app/dns/config.rs
- clash_lib/src/app/dns/resolver/enhanced.rs
- clash_lib/src/app/dns/resolver/mod.rs
- clash_lib/src/app/remote_content_manager/providers/rule_provider/provider.rs
- clash_lib/src/common/mod.rs
- clash_lib/src/common/succinct_set.rs
- clash_lib/src/common/trie.rs
- clash_lib/src/lib.rs
- clash_lib/src/proxy/utils/mod.rs
- clash_lib/src/proxy/utils/test_utils/config_helper.rs
- clash_lib/src/proxy/utils/test_utils/mod.rs
> perf(mem): optimise domain set mem footprint

- Cargo.lock
- Cargo.toml
- clash/Cargo.toml
- clash/src/main.rs
> perf(mem): add dhat heap profile

- clash/tests/data/config/rules.yaml
- clash_lib/src/app/dns/dns_client.rs
- clash_lib/src/app/dns/resolver/enhanced.rs
- clash_lib/src/app/logging.rs
- clash_lib/src/config/def.rs
- clash_lib/src/config/internal/config.rs
- clash_lib/src/proxy/tun/inbound.rs
closed #590 
```
tun:
enable: true
device-id: "dev://utun1989"
route-all: true
gateway: "198.19.0.1/32"
so-mark: 3389
+  dns-hijack: true
```
> feat(dns): support tun dns hijack

- .github/workflows/ci.yml
https://github.com/Watfaq/clash-rs/issues/655
I need a clash-rs binary for my RISC-V dev board so I don't have to manually build the binary every time a new version is released.
Enable RISC-V arch in the test & release GH action, removed it's onion support as per author's instruction.
Note due to cross-rs lacks support for [riscv64gc-unknown-linux-musl](https://doc.rust-lang.org/nightly/rustc/platform-support/riscv64gc-unknown-linux-musl.html), so only the gun version can be built for now.
> ci: enable riscv64 build

- clash_lib/Cargo.toml
- clash_lib/src/app/logging.rs
> build(dep): ios target dep

- clash/tests/data/config/ss.yaml
- clash/tests/data/docker/ss/config.json
- clash_lib/src/proxy/shadowsocks/datagram.rs
> fix(proxy): ss 2022 udp

- clash_ffi/src/lib.rs
An `unsafe` block inside an `unsafe` function is not necessary.
> clash_ffi: remove unnecessary `unsafe` block

- clash_lib/src/app/dispatcher/dispatcher_impl.rs
- clash_lib/src/proxy/socks/inbound/stream.rs
- clash_lib/src/proxy/tproxy/mod.rs
- clash_lib/src/proxy/tun/inbound.rs
use tokio::sync::RwLock<RunMode> instead of std::sync::Mutex<RunMode>, change dispatch_datagram function to async function.
> refactor(dispatcher): use `RwLock<RunMode>` instead of `Mutex<RunMode>`

- clash_lib/src/common/io.rs
- clash_lib/src/proxy/shadowsocks/shadow_tls/stream.rs
- clash_lib/src/proxy/vmess/vmess_impl/stream.rs
re-open of https://github.com/Watfaq/clash-rs/pull/675
there exists some similar code in vmess and shadowtls stream, which i found when i re-read the code. 
the `poll_read_exact` method is especially useful for poll based packet decoding, many proxy projects have their own implement, but there are some ways to make it a general method with a base trait to provide the (inner stream,  BytesMut, read_pos). 
so here comes the base trait `ReadExactBase`, and `ReadExact` trait is automatically implemented for all types which have implemented `ReadExactBase`
```rust
pub trait ReadExactBase {
/// inner stream to be polled
type I: AsyncRead + Unpin;
/// prepare the inner stream, read buffer and read position
fn decompose(&mut self) -> (&mut Self::I, &mut BytesMut, &mut usize);
}
pub trait ReadExt: …
```
> style: make poll_read_exact a general trait

- clash_lib/src/app/dispatcher/dispatcher_impl.rs
- clash_lib/src/config/def.rs
- clash_lib/src/lib.rs
enlarge copy bidrectional buffer size for tcp stream support experimental config of `tcp-buffer-size`
`tokio::io::copy_bidirectional` uses buffer size of 10k; mihomo uses buffer size of 16k/32k (with low/high memory flag)
we currently use buffer size of 4096, and it significantly slowed down the proxy program, especially in direct outbound, where most time was spent on memcpy. 
so we set the buffer size default value to be 16k, this is still a convervative value, but we support more radical value through `expeirment -> tcp-buffer-size`
baseline: iperf3 local to local, without proxy, throughput: 34Gb/s
clash config:
```yaml
mixed-port: 7891
external-controller: 127.0.0.1:19091
log-level: trace
experimental:
tcp-buffer-size: 4096 # change into 16000/32000/50000
rules:
- MATCH,DIRECT
``` …
> perf(throughput): large buffer for copy bidirectional

- .github/workflows/ci.yml
- .gitignore
> ci(coverage): add code coverage

- clash/tests/data/config/tuic.json
- clash_lib/src/common/tls.rs
- clash_lib/src/proxy/tuic/mod.rs
- clash_lib/src/proxy/utils/test_utils/docker_utils/consts.rs
###💡 Background and solution
copy hysteria's `CertVerifyOption` to `common::tls` for general usage of `skip_cer_verify`, rename into `SkipVerifier`
- support `skip_cert_verify` option in tuic
> feat(tuic): support skip_cert_verify, add docker test

- .github/workflows/ci.yml
- clash_lib/src/app/dns/dhcp.rs
- clash_lib/src/app/dns/dns_client.rs
- clash_lib/src/app/dns/runtime.rs
- clash_lib/src/common/http/client.rs
- clash_lib/src/proxy/direct/mod.rs
- clash_lib/src/proxy/hysteria2/mod.rs
- clash_lib/src/proxy/shadowsocks/mod.rs
- clash_lib/src/proxy/socks/inbound/stream.rs
- clash_lib/src/proxy/socks/outbound/mod.rs
- clash_lib/src/proxy/trojan/mod.rs
- clash_lib/src/proxy/tuic/mod.rs
- clash_lib/src/proxy/tuic/types.rs
- clash_lib/src/proxy/utils/platform/unix.rs
- clash_lib/src/proxy/utils/proxy_connector.rs
- clash_lib/src/proxy/utils/socket_helpers.rs
- clash_lib/src/proxy/vmess/mod.rs
- clash_lib/src/proxy/wg/wireguard.rs
SO_MARK and SO_BINDTODEVICE are not usable when targting android.
> fix: remove android target SO_MARK

- Cargo.lock
- Cargo.toml
- clash_lib/Cargo.toml
- clash_lib/src/proxy/shadowsocks/shadow_tls/connector.rs
https://github.com/Watfaq/clash-rs/issues/733
- rename rustls into watfaq-rustls, rename tokio-rustls into tokio-watfaq-rustls
> fix: use watfaq-rustls instead of patched one

- clash/tests/data/config/rule-set-classical.yaml
- clash/tests/data/config/rules.yaml
- clash_lib/src/app/router/mod.rs
- clash_lib/src/app/router/rules/domain_regex.rs
- clash_lib/src/app/router/rules/mod.rs
- clash_lib/src/config/internal/rule.rs
> feat(router): support domain regex

- clash_lib/src/app/dispatcher/dispatcher_impl.rs
- clash_lib/src/app/router/rules/geodata/mod.rs
https://github.com/Watfaq/clash-rs/issues/773
1. add docs to the rather complicated implementation in `dispatch_datagram`
2. use session's original dst addr as the src addr during NAT when receiving the remote packet(needed only for UDP)
> fix(tun): use session's original dst addr as the src addr during udp NAT

- clash_lib/src/config/internal/convert/listener.rs
> fix(listener): pass allow-lan down to listeners

- Cargo.lock
- clash/Cargo.toml
- clash/tests/data/config/shadowquic.yaml
- clash_lib/Cargo.toml
- clash_lib/src/app/outbound/manager.rs
- clash_lib/src/app/remote_content_manager/providers/proxy_provider/proxy_set_provider.rs
- clash_lib/src/config/internal/proxy.rs
- clash_lib/src/proxy/converters/mod.rs
- clash_lib/src/proxy/converters/shadowquic.rs
- clash_lib/src/proxy/mod.rs
- clash_lib/src/proxy/shadowquic/compat.rs
- clash_lib/src/proxy/shadowquic/mod.rs
- clash_lib/src/proxy/utils/test_utils/docker_utils/consts.rs
Hello, this PR implements [shadowquic](https://github.com/spongebob888/shadowquic]) protocol which works similarly to shadowtls but more suitable for QUIC.
I tested personally with socks inbound and TCP/UDP seems to work. Test and doc are not added yet. 
> feat(proxy): add shadowquic protocol

- clash_lib/src/proxy/shadowquic/mod.rs
udp over datagram of shadowquic use quic udp extension to transport udp. It is lossy and CI may failed 
sometimes due to potential packet loss and should be disabled.
The correctness should be guaranteed  by upstream.
> chore: fix shadowquic ci failed

- clash_lib/src/app/inbound/network_listener.rs
- clash_lib/src/app/outbound/manager.rs
> fix(api): append provider proxies to global proxies list

- clash/tests/data/config/rules.yaml
- clash_lib/src/app/dns/config.rs
- clash_lib/src/app/outbound/manager.rs
- clash_lib/src/app/outbound/utils.rs
- clash_lib/src/app/profile/mod.rs
- clash_lib/src/app/remote_content_manager/mod.rs
- clash_lib/src/config/def.rs
- clash_lib/src/config/internal/config.rs
- clash_lib/src/config/internal/convert/mod.rs
- clash_lib/src/config/internal/proxy.rs
- clash_lib/src/proxy/group/mod.rs
- clash_lib/src/proxy/group/smart/config.rs
- clash_lib/src/proxy/group/smart/mod.rs
- clash_lib/src/proxy/group/smart/penalty.rs
- clash_lib/src/proxy/group/smart/preference.rs
- clash_lib/src/proxy/group/smart/state.rs
- clash_lib/src/proxy/group/smart/stats.rs
- clash_lib/src/proxy/mod.rs
- clash_lib/src/session.rs
- docs/clash_doc/struct.ClashConfigDef.html
Inspired by:  
- https://github.com/MetaCubeX/mihomo/commit/3c9d4cecef6f2cef4be3c7a714f4b44adf7a89bc  
- https://kb.nssurge.com/surge-knowledge-base/guidelines/smart-group  
- https://kb.nssurge.com/surge-knowledge-base/zh/guidelines/smart-group (Chinese version)
This PR introduces a new intelligent proxy group type: `smart`, designed for dynamic and adaptive proxy selection based on real-world traffic and proxy behavior. It includes several key mechanisms:
1.  **Penalty-based reliability tracking ([`penalty.rs`](clash_lib/src/proxy/group/smart/penalty.rs))**
*   Each proxy has a `penalty` score that increases exponentially on failure:
```markdown
penalty = (penalty + 1.0) * 2.0
```
*   Penalty decays exponentially over time with a 10-second half-life.
*   Successful connections instantly …
> feat: introduce Smart proxy group for intelligent proxy selection

- Cargo.lock
- clash_lib/Cargo.toml
- clash_lib/src/app/remote_content_manager/providers/rule_provider/mod.rs
- clash_lib/src/app/remote_content_manager/providers/rule_provider/mrs.rs
- clash_lib/src/app/remote_content_manager/providers/rule_provider/provider.rs
- clash_lib/src/app/router/mod.rs
- clash_lib/src/common/succinct_set.rs
- clash_lib/src/common/utils.rs
- clash_lib/src/config/internal/config.rs
- clash_lib/src/config/internal/convert/rule_provider.rs
This pull request enhances the `rule_provider` configuration in accordance with the [Mihomo specification](https://wiki.metacubex.one/en/config/rule-providers/) ([Chinese version](https://wiki.metacubex.one/config/rule-providers/)).
The previous implementation required users to manually specify `path` and `interval`, and did not support the new `mrs` format.
- Added support for the `format` field, including the `mrs` format.
- The `path` field is now optional. If omitted, it defaults to `rules/xxx` with the filename generated via MD5 hash of the source URL.
- The `interval` field is also now optional and defaults to `0` if not specified.
These improvements simplify configuration and enhance compatibility with Mihomo.
- Support for `mrs` format added in `rule_provider`.
- `path` field is …
> feat: Improve rule_provider

- clash_lib/src/app/api/handlers/config.rs
- clash_lib/src/app/inbound/manager.rs
- clash_lib/src/app/inbound/network_listener.rs
- clash_lib/src/config/internal/listener.rs
- clash_lib/tests/api_tests.rs
> feat(proxy): allow setting allow-lan via API

- clash-doc/Cargo.toml
- clash-lib/src/app/dns/dhcp.rs
- clash-lib/src/app/dns/resolver/enhanced.rs
- clash-lib/src/app/dns/runtime.rs
- clash-lib/src/proxy/direct/mod.rs
- clash-lib/src/proxy/hysteria2/mod.rs
- clash-lib/src/proxy/shadowquic/mod.rs
- clash-lib/src/proxy/shadowsocks/inbound/mod.rs
- clash-lib/src/proxy/socks/inbound/stream.rs
- clash-lib/src/proxy/socks/outbound/mod.rs
- clash-lib/src/proxy/tuic/mod.rs
- clash-lib/src/proxy/tuic/types.rs
- clash-lib/src/proxy/tun/inbound.rs
- clash-lib/src/proxy/utils/platform/mod.rs
- clash-lib/src/proxy/utils/platform/unix.rs
- clash-lib/src/proxy/utils/proxy_connector.rs
- clash-lib/src/proxy/utils/socket_helpers.rs
best effort to create proper family of socket for UDP connections
> fix(proxy): added family hint for new_udp_socket

- Cargo.lock
- clash-lib/Cargo.toml
- clash-lib/src/config/internal/config.rs
- clash-lib/src/proxy/http/inbound/mod.rs
- clash-lib/src/proxy/mixed/mod.rs
- clash-lib/src/proxy/shadowsocks/inbound/mod.rs
- clash-lib/src/proxy/socks/inbound/mod.rs
- clash-lib/src/proxy/socks/socks5.rs
- clash-lib/src/proxy/tproxy/ip6tables.sh
- clash-lib/src/proxy/tproxy/iptables.sh
- clash-lib/src/proxy/tproxy/mod.rs
- clash-lib/src/proxy/utils/socket_helpers.rs
As have been discussed, this PR is a draft to support dual stack. 
Finally I take the first approach. Namely using `[::]:port` as a dual stack socket.
To achieve this "Ipv6" Addess is added to `BindAdress`. Unfortunately. Binding to ipv6 address forces us to also implement dualstack for socks/http/mixed. 
1. Adding ipv6 bind address
2. Adding TProxy dualstack
3. The socks outbound associate destination is 0.0.0.0:0, changed to [::]:0 if it's ipv6
4. TProxy UDP sending pack to local is using TProxy as src addr. Create a new udp to send udp packets back.
5. Adding dualstack for http/mixed/ss inbound\
6. Allowlan for TProxy is commented. No trivial way to get local address
> feat: adding dual stack

- clash-lib/Cargo.toml
- clash-lib/src/app/logging.rs
> build: make tracing optional

- clash-lib/src/proxy/shadowquic/mod.rs
#918
Due to change of `new_udp_socket` function. UDP socket is not bound for shadowquic outbound. It works on
linux but failed on windows. 
This PR should fix
> fix(proxy): udp not bound for shadowquic #918
